server:
  port: 8082

spring:
  application:
    name: k12-learning-service
  config:
    import: optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:false}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml

management:
  endpoints:
    web:
      exposure:
        include: health,info
