server:
  port: 8081

spring:
  application:
    name: k12-iam-service
  datasource:
    url: jdbc:mysql://${K12_AUTH_DB_HOST:122.51.54.52}:${K12_AUTH_DB_PORT:3306}/${K12_AUTH_DB_NAME:k12_auth}?useUnicode=true&characterEncoding=utf8&useSSL=${K12_DB_USE_SSL:false}&allowPublicKeyRetrieval=${K12_DB_ALLOW_PUBLIC_KEY_RETRIEVAL:true}&serverTimezone=Asia/Shanghai
    username: ${K12_AUTH_DB_USERNAME:k12}
    password: ${K12_AUTH_DB_PASSWORD:K12@123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        enabled: ${NACOS_CONFIG_ENABLED:false}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.k12.platform.iam.model
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

k12:
  security:
    jwt:
      issuer: ${K12_JWT_ISSUER:k12-platform}
      secret: ${K12_JWT_SECRET:k12-platform-dev-secret-change-me-2026-very-long-key}
      access-token-ttl: ${K12_JWT_ACCESS_TOKEN_TTL:30m}

management:
  endpoints:
    web:
      exposure:
        include: health,info
