"""Generate ai_literacy_catalog.json with categories + ~300 topic nodes.

Run with the agent-runtime Python env (not the Java learning-service module):

  cd ai-services/k12-agent-runtime
  uv run python scripts/generate_knowledge_catalog.py
"""

from __future__ import annotations

import json
from pathlib import Path

CATEGORIES = [
    ("ai_overview", "人工智能概论", "PRIMARY_UPPER", 1),
    ("data_literacy", "数据素养", "PRIMARY_UPPER", 1),
    ("computing", "计算思维", "PRIMARY_UPPER", 1),
    ("algorithms", "算法与数据结构", "JUNIOR_HIGH", 2),
    ("programming", "编程基础", "PRIMARY_UPPER", 1),
    ("machine_learning", "机器学习", "JUNIOR_HIGH", 2),
    ("generative_ai", "生成式人工智能", "JUNIOR_HIGH", 2),
    ("computer_vision", "计算机视觉", "JUNIOR_HIGH", 2),
    ("nlp", "自然语言处理", "JUNIOR_HIGH", 2),
    ("ethics_safety", "AI伦理与安全", "PRIMARY_UPPER", 2),
    ("digital_citizenship", "数字公民", "PRIMARY_UPPER", 1),
    ("robotics_iot", "机器人与物联网", "JUNIOR_HIGH", 2),
]

TOPICS: dict[str, list[tuple[str, str, str, int]]] = {
    "ai_overview": [
        ("what_is_ai", "什么是人工智能", "PRIMARY_UPPER", 1),
        ("ai_history", "人工智能简史", "JUNIOR_HIGH", 2),
        ("weak_strong_ai", "弱人工智能与强人工智能", "JUNIOR_HIGH", 2),
        ("ai_vs_human", "人工智能与人类智能", "PRIMARY_UPPER", 1),
        ("ai_applications", "生活中的人工智能", "PRIMARY_UPPER", 1),
        ("ai_perception", "感知智能入门", "JUNIOR_HIGH", 2),
        ("ai_reasoning", "推理与决策入门", "JUNIOR_HIGH", 2),
        ("ai_learning", "学习能力从哪里来", "PRIMARY_UPPER", 2),
        ("ai_limitations", "人工智能的局限", "PRIMARY_UPPER", 2),
        ("ai_jobs", "AI与未来职业", "JUNIOR_HIGH", 2),
        ("turing_test", "图灵测试", "JUNIOR_HIGH", 2),
        ("expert_systems", "专家系统简介", "SENIOR_HIGH", 3),
        ("knowledge_representation", "知识表示入门", "SENIOR_HIGH", 3),
        ("search_planning", "搜索与规划入门", "SENIOR_HIGH", 3),
        ("multi_agent", "多智能体简介", "SENIOR_HIGH", 4),
        ("embodied_ai", "具身智能简介", "SENIOR_HIGH", 4),
        ("ai_benchmarks", "如何评价AI能力", "JUNIOR_HIGH", 3),
        ("ai_open_source", "开源模型与工具", "SENIOR_HIGH", 3),
        ("ai_cloud_edge", "云端与端侧AI", "SENIOR_HIGH", 3),
        ("ai_literacy_mindset", "AI素养心态", "PRIMARY_UPPER", 1),
        ("symbol_connectionism", "符号主义与连接主义", "SENIOR_HIGH", 4),
        ("general_ai_myths", "关于AI的常见误解", "PRIMARY_UPPER", 1),
        ("ai_in_school", "校园里的AI应用", "PRIMARY_UPPER", 1),
        ("ai_assistive", "AI辅助学习工具", "PRIMARY_UPPER", 1),
        ("ai_creativity", "AI与创造力", "JUNIOR_HIGH", 2),
    ],
    "data_literacy": [
        ("what_is_data", "什么是数据", "PRIMARY_UPPER", 1),
        ("privacy_basics", "数据与隐私入门", "PRIMARY_UPPER", 2),
        ("data_types", "数据类型：数字文字图片", "PRIMARY_UPPER", 1),
        ("data_collection", "数据如何收集", "PRIMARY_UPPER", 1),
        ("data_vs_info", "数据与信息的区别", "PRIMARY_UPPER", 1),
        ("data_quality", "数据质量与缺失", "JUNIOR_HIGH", 2),
        ("data_cleaning", "数据清洗入门", "JUNIOR_HIGH", 2),
        ("data_visualization", "数据可视化入门", "PRIMARY_UPPER", 2),
        ("charts_basics", "常见图表怎么读", "PRIMARY_UPPER", 1),
        ("mean_median", "平均数与中位数", "PRIMARY_UPPER", 2),
        ("sampling", "抽样与代表性", "JUNIOR_HIGH", 2),
        ("correlation_causation", "相关不等于因果", "JUNIOR_HIGH", 3),
        ("big_data_basics", "大数据是什么", "JUNIOR_HIGH", 2),
        ("open_data", "开放数据与公共数据", "JUNIOR_HIGH", 2),
        ("personal_data", "个人数据有哪些", "PRIMARY_UPPER", 1),
        ("consent_basics", "知情同意入门", "PRIMARY_UPPER", 2),
        ("data_security", "数据安全基础", "JUNIOR_HIGH", 2),
        ("anonymization", "脱敏与匿名化", "JUNIOR_HIGH", 3),
        ("data_lifecycle", "数据生命周期", "SENIOR_HIGH", 3),
        ("metadata", "元数据是什么", "JUNIOR_HIGH", 2),
        ("database_basics", "数据库入门概念", "JUNIOR_HIGH", 2),
        ("csv_tables", "表格数据与CSV", "PRIMARY_UPPER", 1),
        ("sensor_data", "传感器数据", "PRIMARY_UPPER", 2),
        ("survey_design", "简单问卷设计", "JUNIOR_HIGH", 2),
        ("data_storytelling", "用数据讲故事", "JUNIOR_HIGH", 2),
        ("bias_in_data", "数据中的偏见", "JUNIOR_HIGH", 3),
        ("statistics_basics", "统计思维入门", "JUNIOR_HIGH", 2),
        ("probability_basics", "概率直觉", "JUNIOR_HIGH", 2),
        ("data_ethics", "数据伦理", "JUNIOR_HIGH", 2),
        ("gdpr_minors", "未成年人数据保护", "JUNIOR_HIGH", 2),
    ],
    "computing": [
        ("algorithm_basics", "算法入门", "PRIMARY_UPPER", 2),
        ("loop_basics", "循环基础", "JUNIOR_HIGH", 2),
        ("sequence", "顺序结构", "PRIMARY_UPPER", 1),
        ("branching", "分支判断", "PRIMARY_UPPER", 1),
        ("decomposition", "问题分解", "PRIMARY_UPPER", 1),
        ("pattern_recognition", "模式识别思维", "PRIMARY_UPPER", 1),
        ("abstraction", "抽象思维", "JUNIOR_HIGH", 2),
        ("debugging", "调试与查错", "PRIMARY_UPPER", 2),
        ("pseudocode", "伪代码入门", "JUNIOR_HIGH", 2),
        ("flowcharts", "流程图", "PRIMARY_UPPER", 1),
        ("computational_thinking", "计算思维概述", "PRIMARY_UPPER", 1),
        ("input_output", "输入与输出", "PRIMARY_UPPER", 1),
        ("variables", "变量与赋值", "PRIMARY_UPPER", 1),
        ("boolean_logic", "布尔逻辑", "JUNIOR_HIGH", 2),
        ("nested_loops", "嵌套循环", "JUNIOR_HIGH", 2),
        ("recursion_intro", "递归直觉", "SENIOR_HIGH", 3),
        ("complexity_intro", "时间复杂度直觉", "SENIOR_HIGH", 3),
        ("modularity", "模块化思想", "JUNIOR_HIGH", 2),
        ("state_machines", "状态与转换", "JUNIOR_HIGH", 3),
        ("event_driven", "事件驱动思维", "JUNIOR_HIGH", 2),
        ("simulation", "模拟与仿真", "JUNIOR_HIGH", 2),
        ("automation", "自动化是什么", "PRIMARY_UPPER", 1),
        ("binary_basics", "二进制入门", "JUNIOR_HIGH", 2),
        ("encoding_text", "文字如何编码", "JUNIOR_HIGH", 2),
        ("compression_intro", "压缩直觉", "JUNIOR_HIGH", 2),
        ("networks_basics", "网络基础概念", "JUNIOR_HIGH", 2),
        ("client_server", "客户端与服务器", "JUNIOR_HIGH", 2),
        ("apis_intro", "API是什么", "SENIOR_HIGH", 3),
        ("version_control_idea", "版本管理思想", "SENIOR_HIGH", 3),
        ("testing_basics", "测试与验证", "JUNIOR_HIGH", 2),
    ],
    "algorithms": [
        ("bubble_sort", "冒泡排序", "JUNIOR_HIGH", 2),
        ("selection_sort", "选择排序", "JUNIOR_HIGH", 2),
        ("insertion_sort", "插入排序", "JUNIOR_HIGH", 2),
        ("merge_sort", "归并排序入门", "SENIOR_HIGH", 3),
        ("quick_sort", "快速排序入门", "SENIOR_HIGH", 3),
        ("linear_search", "线性查找", "PRIMARY_UPPER", 2),
        ("binary_search", "二分查找", "JUNIOR_HIGH", 3),
        ("hashing_intro", "哈希查找直觉", "SENIOR_HIGH", 3),
        ("stack_queue", "栈与队列", "JUNIOR_HIGH", 2),
        ("linked_list", "链表概念", "SENIOR_HIGH", 3),
        ("trees_intro", "树结构入门", "SENIOR_HIGH", 3),
        ("graphs_intro", "图结构入门", "SENIOR_HIGH", 3),
        ("bfs_dfs", "广度与深度优先", "SENIOR_HIGH", 3),
        ("shortest_path", "最短路径直觉", "SENIOR_HIGH", 4),
        ("greedy_intro", "贪心思想", "SENIOR_HIGH", 3),
        ("dp_intro", "动态规划直觉", "SENIOR_HIGH", 4),
        ("divide_conquer", "分治思想", "SENIOR_HIGH", 3),
        ("sorting_compare", "排序算法比较", "JUNIOR_HIGH", 3),
        ("stable_sort", "稳定性是什么", "SENIOR_HIGH", 3),
        ("counting_sort", "计数排序直觉", "SENIOR_HIGH", 3),
        ("heap_intro", "堆与优先队列", "SENIOR_HIGH", 4),
        ("string_match", "字符串匹配入门", "JUNIOR_HIGH", 3),
        ("pathfinding_game", "寻路与游戏AI", "JUNIOR_HIGH", 2),
        ("optimization_intro", "优化问题入门", "SENIOR_HIGH", 3),
        ("randomized_algo", "随机算法直觉", "SENIOR_HIGH", 3),
        ("parallel_idea", "并行计算直觉", "SENIOR_HIGH", 3),
        ("cache_locality", "局部性原理", "SENIOR_HIGH", 4),
        ("correctness", "算法正确性", "SENIOR_HIGH", 3),
        ("brute_force", "暴力枚举", "JUNIOR_HIGH", 2),
        ("backtracking", "回溯入门", "SENIOR_HIGH", 3),
        ("two_pointers", "双指针思想", "SENIOR_HIGH", 3),
        ("sliding_window", "滑动窗口", "SENIOR_HIGH", 3),
        ("prefix_sum", "前缀和", "SENIOR_HIGH", 3),
        ("bit_tricks", "位运算直觉", "SENIOR_HIGH", 3),
        ("topo_sort", "拓扑排序直觉", "SENIOR_HIGH", 4),
        ("union_find", "并查集直觉", "SENIOR_HIGH", 4),
        ("mst_intro", "最小生成树直觉", "SENIOR_HIGH", 4),
        ("np_intro", "难解问题直觉", "SENIOR_HIGH", 4),
        ("algo_in_life", "生活中的算法", "PRIMARY_UPPER", 1),
        ("recipe_as_algo", "食谱也是算法", "PRIMARY_UPPER", 1),
    ],
    "programming": [
        ("scratch_basics", "图形化编程入门", "PRIMARY_UPPER", 1),
        ("python_intro", "Python入门", "JUNIOR_HIGH", 2),
        ("functions", "函数与复用", "JUNIOR_HIGH", 2),
        ("lists_arrays", "列表与数组", "JUNIOR_HIGH", 2),
        ("dicts_maps", "字典与映射", "JUNIOR_HIGH", 2),
        ("strings", "字符串处理", "JUNIOR_HIGH", 2),
        ("file_io", "文件读写入门", "JUNIOR_HIGH", 2),
        ("exceptions", "异常处理入门", "SENIOR_HIGH", 3),
        ("oop_intro", "面向对象入门", "SENIOR_HIGH", 3),
        ("ide_basics", "编辑器与运行环境", "PRIMARY_UPPER", 1),
        ("comments_docs", "注释与可读性", "PRIMARY_UPPER", 1),
        ("naming", "命名规范", "PRIMARY_UPPER", 1),
        ("libraries", "库与第三方包", "JUNIOR_HIGH", 2),
        ("packages", "模块与包", "SENIOR_HIGH", 3),
        ("git_basics", "Git基础", "SENIOR_HIGH", 3),
        ("web_html_css", "网页结构入门", "JUNIOR_HIGH", 2),
        ("js_basics", "JavaScript入门", "SENIOR_HIGH", 3),
        ("sql_intro", "SQL查询入门", "SENIOR_HIGH", 3),
        ("gui_basics", "简单图形界面", "JUNIOR_HIGH", 2),
        ("game_loop", "游戏循环", "JUNIOR_HIGH", 2),
        ("sensors_code", "读传感器数据编程", "JUNIOR_HIGH", 2),
        ("turtle_graphics", "海龟绘图", "PRIMARY_UPPER", 1),
        ("conditionals_practice", "条件语句练习", "PRIMARY_UPPER", 1),
        ("loops_practice", "循环练习", "PRIMARY_UPPER", 1),
        ("debugging_tools", "调试工具使用", "JUNIOR_HIGH", 2),
        ("unit_test_idea", "单元测试思想", "SENIOR_HIGH", 3),
        ("code_review", "代码评审文化", "SENIOR_HIGH", 3),
        ("security_coding", "安全编码意识", "SENIOR_HIGH", 3),
        ("performance_basics", "性能意识", "SENIOR_HIGH", 3),
        ("concurrency_intro", "并发入门", "SENIOR_HIGH", 4),
        ("rest_client", "调用网络接口", "SENIOR_HIGH", 3),
        ("json_data", "JSON数据格式", "JUNIOR_HIGH", 2),
        ("regex_intro", "正则表达式入门", "SENIOR_HIGH", 3),
        ("cli_basics", "命令行基础", "JUNIOR_HIGH", 2),
        ("project_structure", "项目结构组织", "SENIOR_HIGH", 3),
    ],
    "machine_learning": [
        ("features_labels", "特征与标签", "JUNIOR_HIGH", 2),
        ("supervised_learning", "监督学习", "JUNIOR_HIGH", 3),
        ("classification_regression", "分类与回归", "JUNIOR_HIGH", 3),
        ("train_test_split", "训练/测试划分", "JUNIOR_HIGH", 3),
        ("overfitting", "过拟合", "SENIOR_HIGH", 4),
        ("image_classification", "图像分类", "JUNIOR_HIGH", 3),
        ("data_bias", "数据偏差", "JUNIOR_HIGH", 3),
        ("neural_network_basics", "神经网络入门", "SENIOR_HIGH", 4),
        ("unsupervised", "无监督学习入门", "SENIOR_HIGH", 3),
        ("clustering", "聚类入门", "SENIOR_HIGH", 3),
        ("reinforcement_intro", "强化学习直觉", "SENIOR_HIGH", 4),
        ("loss_function", "损失函数直觉", "SENIOR_HIGH", 3),
        ("gradient_descent", "梯度下降直觉", "SENIOR_HIGH", 4),
        ("metrics_accuracy", "准确率与召回", "SENIOR_HIGH", 3),
        ("confusion_matrix", "混淆矩阵", "SENIOR_HIGH", 3),
        ("feature_engineering", "特征工程入门", "SENIOR_HIGH", 3),
        ("normalization", "归一化与标准化", "SENIOR_HIGH", 3),
        ("cross_validation", "交叉验证", "SENIOR_HIGH", 3),
        ("ensemble_intro", "集成学习直觉", "SENIOR_HIGH", 4),
        ("decision_tree", "决策树入门", "JUNIOR_HIGH", 3),
        ("knn_intro", "K近邻入门", "JUNIOR_HIGH", 3),
        ("linear_model", "线性模型直觉", "SENIOR_HIGH", 3),
        ("svm_intro", "支持向量机直觉", "SENIOR_HIGH", 4),
        ("bayes_intro", "朴素贝叶斯直觉", "SENIOR_HIGH", 3),
        ("dim_reduction", "降维直觉", "SENIOR_HIGH", 4),
        ("transfer_learning", "迁移学习入门", "SENIOR_HIGH", 3),
        ("model_deployment", "模型上线概念", "SENIOR_HIGH", 3),
        ("labeling_cost", "标注成本", "JUNIOR_HIGH", 2),
        ("active_learning", "主动学习直觉", "SENIOR_HIGH", 4),
        ("data_augmentation", "数据增强", "SENIOR_HIGH", 3),
        ("imbalanced_data", "类别不平衡", "SENIOR_HIGH", 3),
        ("ml_pipeline", "机器学习流水线", "SENIOR_HIGH", 3),
        ("hyperparams", "超参数是什么", "SENIOR_HIGH", 3),
        ("underfitting", "欠拟合", "SENIOR_HIGH", 3),
        ("regularization", "正则化直觉", "SENIOR_HIGH", 4),
        ("embedding_intro", "向量表示入门", "SENIOR_HIGH", 3),
        ("recommenders", "推荐系统入门", "JUNIOR_HIGH", 3),
        ("anomaly_detection", "异常检测入门", "SENIOR_HIGH", 3),
        ("time_series", "时间序列入门", "SENIOR_HIGH", 3),
        ("ml_vs_rules", "规则系统与学习系统", "JUNIOR_HIGH", 2),
        ("dataset_split_leak", "数据泄漏", "SENIOR_HIGH", 3),
        ("baselines", "基线模型", "SENIOR_HIGH", 3),
        ("error_analysis", "错误分析", "SENIOR_HIGH", 3),
        ("human_in_loop", "人机协同标注", "JUNIOR_HIGH", 2),
        ("ml_cards", "模型卡片意识", "SENIOR_HIGH", 3),
    ],
    "generative_ai": [
        ("prompt_basics", "提示词基础", "PRIMARY_UPPER", 2),
        ("hallucination", "大模型幻觉", "JUNIOR_HIGH", 3),
        ("responsible_use", "负责任使用生成式AI", "PRIMARY_UPPER", 2),
        ("copyright_originality", "版权与原创", "JUNIOR_HIGH", 3),
        ("llm_basics", "大语言模型是什么", "JUNIOR_HIGH", 2),
        ("tokens", "Token与上下文窗口", "SENIOR_HIGH", 3),
        ("temperature", "温度与随机性", "SENIOR_HIGH", 3),
        ("few_shot", "少样本提示", "JUNIOR_HIGH", 3),
        ("chain_of_thought", "思维链提示", "SENIOR_HIGH", 3),
        ("system_prompt", "系统提示词", "SENIOR_HIGH", 3),
        ("rag_basics", "检索增强生成入门", "SENIOR_HIGH", 3),
        ("agents_basics", "智能体入门", "SENIOR_HIGH", 3),
        ("tool_use", "工具调用", "SENIOR_HIGH", 3),
        ("multimodal", "多模态生成", "JUNIOR_HIGH", 3),
        ("image_gen", "AI绘画入门", "JUNIOR_HIGH", 2),
        ("music_gen", "AI音乐入门", "JUNIOR_HIGH", 2),
        ("code_gen", "AI写代码", "JUNIOR_HIGH", 2),
        ("summarization", "摘要与改写", "PRIMARY_UPPER", 2),
        ("translation_ai", "AI翻译", "PRIMARY_UPPER", 1),
        ("chatbots", "聊天机器人", "PRIMARY_UPPER", 1),
        ("prompt_injection", "提示注入风险", "SENIOR_HIGH", 3),
        ("jailbreak_risk", "越狱与滥用风险", "SENIOR_HIGH", 3),
        ("eval_outputs", "如何评价生成结果", "JUNIOR_HIGH", 2),
        ("cite_sources", "要求引用来源", "JUNIOR_HIGH", 2),
        ("role_play_prompt", "角色设定提示", "PRIMARY_UPPER", 2),
        ("structured_output", "结构化输出", "SENIOR_HIGH", 3),
        ("fine_tuning_idea", "微调是什么", "SENIOR_HIGH", 3),
        ("pretraining_idea", "预训练是什么", "SENIOR_HIGH", 3),
        ("alignment", "对齐与价值观", "SENIOR_HIGH", 3),
        ("rlhf_intro", "人类反馈强化学习", "SENIOR_HIGH", 4),
        ("watermarking", "生成内容水印", "SENIOR_HIGH", 3),
        ("deepfake_awareness", "深度伪造识别", "JUNIOR_HIGH", 2),
        ("ai_writing_school", "作业中的AI写作", "PRIMARY_UPPER", 2),
        ("personalization_risk", "个性化与信息茧房", "JUNIOR_HIGH", 2),
        ("cost_energy", "算力与能耗意识", "SENIOR_HIGH", 3),
        ("open_vs_closed", "开源与闭源模型", "SENIOR_HIGH", 3),
        ("safety_filters", "安全过滤机制", "JUNIOR_HIGH", 2),
        ("memory_privacy", "对话记忆与隐私", "JUNIOR_HIGH", 2),
        ("prompt_patterns", "常用提示词模式", "JUNIOR_HIGH", 2),
        ("critique_revise", "批评与修订循环", "JUNIOR_HIGH", 2),
    ],
    "computer_vision": [
        ("pixels", "像素与图像", "PRIMARY_UPPER", 1),
        ("color_spaces", "颜色空间入门", "JUNIOR_HIGH", 2),
        ("filters", "图像滤波直觉", "JUNIOR_HIGH", 2),
        ("edges", "边缘检测直觉", "JUNIOR_HIGH", 2),
        ("object_detection", "目标检测入门", "JUNIOR_HIGH", 3),
        ("segmentation", "图像分割入门", "SENIOR_HIGH", 3),
        ("face_recognition", "人脸识别与隐私", "JUNIOR_HIGH", 2),
        ("ocr", "文字识别OCR", "PRIMARY_UPPER", 2),
        ("pose_estimation", "姿态估计入门", "SENIOR_HIGH", 3),
        ("video_basics", "视频理解入门", "SENIOR_HIGH", 3),
        ("augmentation_vision", "视觉数据增强", "SENIOR_HIGH", 3),
        ("cnn_intro", "卷积神经网络直觉", "SENIOR_HIGH", 4),
        ("cameras", "摄像头与采集", "PRIMARY_UPPER", 1),
        ("lighting", "光照对识别的影响", "PRIMARY_UPPER", 1),
        ("dataset_images", "图像数据集", "JUNIOR_HIGH", 2),
        ("adversarial_images", "对抗样本直觉", "SENIOR_HIGH", 4),
        ("medical_imaging", "医学影像AI简介", "SENIOR_HIGH", 3),
        ("autonomous_vision", "自动驾驶中的视觉", "SENIOR_HIGH", 3),
        ("ar_basics", "增强现实入门", "JUNIOR_HIGH", 2),
        ("cv_ethics", "视觉技术伦理", "JUNIOR_HIGH", 2),
        ("barcode_qr", "条码与二维码", "PRIMARY_UPPER", 1),
        ("image_search", "以图搜图", "PRIMARY_UPPER", 2),
        ("style_transfer", "风格迁移", "JUNIOR_HIGH", 2),
        ("depth_estimation", "深度估计直觉", "SENIOR_HIGH", 3),
        ("tracking", "目标跟踪入门", "SENIOR_HIGH", 3),
    ],
    "nlp": [
        ("text_tokenize", "分词入门", "JUNIOR_HIGH", 2),
        ("bag_of_words", "词袋模型直觉", "SENIOR_HIGH", 3),
        ("word_embeddings", "词向量入门", "SENIOR_HIGH", 3),
        ("sentiment", "情感分析入门", "JUNIOR_HIGH", 2),
        ("ner", "命名实体识别", "SENIOR_HIGH", 3),
        ("machine_translation", "机器翻译原理简介", "JUNIOR_HIGH", 2),
        ("speech_to_text", "语音转文字", "PRIMARY_UPPER", 2),
        ("text_to_speech", "文字转语音", "PRIMARY_UPPER", 2),
        ("topic_modeling", "主题模型直觉", "SENIOR_HIGH", 4),
        ("qa_systems", "问答系统入门", "JUNIOR_HIGH", 2),
        ("information_retrieval", "信息检索基础", "JUNIOR_HIGH", 2),
        ("spell_check", "拼写检查", "PRIMARY_UPPER", 1),
        ("grammar_assist", "语法辅助工具", "PRIMARY_UPPER", 1),
        ("hate_speech", "有害内容识别", "JUNIOR_HIGH", 2),
        ("language_bias", "语言中的偏见", "JUNIOR_HIGH", 2),
        ("multilingual", "多语言处理", "SENIOR_HIGH", 3),
        ("dialogue_systems", "对话系统结构", "SENIOR_HIGH", 3),
        ("summarization_nlp", "文本摘要技术", "JUNIOR_HIGH", 2),
        ("transformers_intro", "Transformer直觉", "SENIOR_HIGH", 4),
        ("attention_intro", "注意力机制直觉", "SENIOR_HIGH", 4),
        ("corpus", "语料库是什么", "JUNIOR_HIGH", 2),
        ("stopwords", "停用词", "JUNIOR_HIGH", 2),
        ("tfidf", "TF-IDF直觉", "SENIOR_HIGH", 3),
        ("intent_slot", "意图与槽位", "SENIOR_HIGH", 3),
        ("chat_eval", "对话质量评价", "SENIOR_HIGH", 3),
    ],
    "ethics_safety": [
        ("ai_ethics_intro", "AI伦理入门", "PRIMARY_UPPER", 2),
        ("fairness", "公平性", "JUNIOR_HIGH", 2),
        ("transparency", "透明与可解释", "JUNIOR_HIGH", 2),
        ("accountability", "问责机制", "JUNIOR_HIGH", 2),
        ("safety_first", "安全优先原则", "PRIMARY_UPPER", 1),
        ("dual_use", "两用技术风险", "SENIOR_HIGH", 3),
        ("misinformation", "虚假信息与AI", "JUNIOR_HIGH", 2),
        ("surveillance", "监控与自由", "JUNIOR_HIGH", 2),
        ("algorithmic_discrimination", "算法歧视", "JUNIOR_HIGH", 3),
        ("child_safety", "未成年人保护", "PRIMARY_UPPER", 1),
        ("content_moderation", "内容审核", "JUNIOR_HIGH", 2),
        ("red_teaming", "红队测试简介", "SENIOR_HIGH", 3),
        ("incident_response", "安全事件应对", "SENIOR_HIGH", 3),
        ("value_alignment", "价值对齐", "SENIOR_HIGH", 3),
        ("environmental_cost", "环境成本", "JUNIOR_HIGH", 2),
        ("labor_impact", "就业影响讨论", "JUNIOR_HIGH", 2),
        ("global_governance", "全球治理简介", "SENIOR_HIGH", 3),
        ("standards_compliance", "标准与合规", "SENIOR_HIGH", 3),
        ("human_oversight", "人类监督", "PRIMARY_UPPER", 2),
        ("refuse_harmful", "拒绝有害请求", "PRIMARY_UPPER", 1),
        ("privacy_by_design", "隐私设计", "JUNIOR_HIGH", 2),
        ("consent_ai", "AI场景知情同意", "JUNIOR_HIGH", 2),
        ("shadow_ai", "影子AI风险", "SENIOR_HIGH", 3),
        ("model_theft", "模型窃取风险", "SENIOR_HIGH", 3),
        ("secure_deployment", "安全部署意识", "SENIOR_HIGH", 3),
    ],
    "digital_citizenship": [
        ("online_identity", "网络身份", "PRIMARY_UPPER", 1),
        ("password_hygiene", "密码与账号安全", "PRIMARY_UPPER", 1),
        ("phishing", "钓鱼与诈骗识别", "PRIMARY_UPPER", 1),
        ("cyberbullying", "网络欺凌", "PRIMARY_UPPER", 1),
        ("digital_footprint", "数字足迹", "PRIMARY_UPPER", 1),
        ("media_literacy", "媒介素养", "PRIMARY_UPPER", 1),
        ("fake_news", "辨别假新闻", "PRIMARY_UPPER", 2),
        ("source_checking", "查证来源", "PRIMARY_UPPER", 2),
        ("screen_time", "屏幕时间管理", "PRIMARY_UPPER", 1),
        ("copyright_basics", "版权基础", "PRIMARY_UPPER", 2),
        ("creative_commons", "知识共享许可", "JUNIOR_HIGH", 2),
        ("netiquette", "网络礼仪", "PRIMARY_UPPER", 1),
        ("collaboration_online", "在线协作", "PRIMARY_UPPER", 1),
        ("digital_wellbeing", "数字健康", "PRIMARY_UPPER", 1),
        ("accessibility", "无障碍意识", "JUNIOR_HIGH", 2),
        ("inclusive_design", "包容性设计", "JUNIOR_HIGH", 2),
        ("community_norms", "社区规范", "PRIMARY_UPPER", 1),
        ("reporting_abuse", "举报不良内容", "PRIMARY_UPPER", 1),
        ("device_permissions", "应用权限管理", "PRIMARY_UPPER", 1),
        ("public_wifi", "公共WiFi风险", "JUNIOR_HIGH", 2),
        ("two_factor_auth", "双因素认证", "JUNIOR_HIGH", 2),
        ("backup_basics", "备份意识", "PRIMARY_UPPER", 1),
        ("software_updates", "及时更新", "PRIMARY_UPPER", 1),
        ("sharing_wisely", "明智分享", "PRIMARY_UPPER", 1),
        ("critical_thinking", "批判性思维上网", "PRIMARY_UPPER", 2),
    ],
    "robotics_iot": [
        ("robot_basics", "机器人是什么", "PRIMARY_UPPER", 1),
        ("sensors_actuators", "传感器与执行器", "PRIMARY_UPPER", 1),
        ("iot_basics", "物联网入门", "JUNIOR_HIGH", 2),
        ("smart_home", "智能家居", "PRIMARY_UPPER", 1),
        ("drone_basics", "无人机简介", "JUNIOR_HIGH", 2),
        ("slam_intro", "定位与建图直觉", "SENIOR_HIGH", 4),
        ("path_planning_robot", "机器人路径规划", "SENIOR_HIGH", 3),
        ("human_robot", "人机协作", "JUNIOR_HIGH", 2),
        ("safety_robots", "机器人安全", "PRIMARY_UPPER", 2),
        ("edge_devices", "边缘设备", "SENIOR_HIGH", 3),
        ("mqtt_intro", "设备消息协议简介", "SENIOR_HIGH", 3),
        ("firmware", "固件概念", "SENIOR_HIGH", 3),
        ("calibration", "标定意识", "JUNIOR_HIGH", 2),
        ("swarm_robots", "群体机器人简介", "SENIOR_HIGH", 4),
        ("wearables", "可穿戴设备", "PRIMARY_UPPER", 1),
        ("industrial_robots", "工业机器人简介", "JUNIOR_HIGH", 2),
        ("soft_robotics", "软体机器人简介", "SENIOR_HIGH", 3),
        ("energy_robots", "能源与续航", "JUNIOR_HIGH", 2),
        ("ethics_robots", "机器人伦理", "JUNIOR_HIGH", 2),
        ("makerspace", "创客与动手实践", "PRIMARY_UPPER", 1),
        ("arduino_idea", "开源硬件思想", "JUNIOR_HIGH", 2),
        ("remote_sensing", "遥感与感知网络", "SENIOR_HIGH", 3),
        ("digital_twin", "数字孪生简介", "SENIOR_HIGH", 3),
        ("automation_factory", "工厂自动化", "JUNIOR_HIGH", 2),
        ("assistive_robots", "辅助机器人", "PRIMARY_UPPER", 2),
    ],
}

LEGACY = {
    ("data_literacy", "what_is_data"): "data_literacy.what_is_data",
    ("data_literacy", "privacy_basics"): "data_literacy.privacy_basics",
    ("computing", "algorithm_basics"): "computing.algorithm_basics",
    ("computing", "loop_basics"): "computing.loop_basics",
    ("machine_learning", "features_labels"): "machine_learning.features_labels",
    ("machine_learning", "supervised_learning"): "machine_learning.supervised_learning",
    ("machine_learning", "classification_regression"): "machine_learning.classification_regression",
    ("machine_learning", "train_test_split"): "machine_learning.train_test_split",
    ("machine_learning", "overfitting"): "machine_learning.overfitting",
    ("machine_learning", "image_classification"): "machine_learning.image_classification",
    ("machine_learning", "data_bias"): "machine_learning.data_bias",
    ("machine_learning", "neural_network_basics"): "machine_learning.neural_network_basics",
    ("generative_ai", "prompt_basics"): "generative_ai.prompt_basics",
    ("generative_ai", "hallucination"): "generative_ai.hallucination",
    ("generative_ai", "responsible_use"): "generative_ai.responsible_use",
    ("generative_ai", "copyright_originality"): "generative_ai.copyright_originality",
    ("algorithms", "bubble_sort"): "sorting.bubble_sort",
    ("algorithms", "selection_sort"): "sorting.selection_sort",
    ("algorithms", "insertion_sort"): "sorting.insertion_sort",
    ("algorithms", "linear_search"): "searching.linear_search",
    ("algorithms", "binary_search"): "searching.binary_search",
}

PREREQS = [
    ("data_literacy.what_is_data", "computing.algorithm_basics"),
    ("computing.algorithm_basics", "computing.loop_basics"),
    ("computing.loop_basics", "machine_learning.features_labels"),
    ("machine_learning.features_labels", "machine_learning.supervised_learning"),
    ("machine_learning.supervised_learning", "machine_learning.classification_regression"),
    ("machine_learning.supervised_learning", "machine_learning.train_test_split"),
    ("machine_learning.train_test_split", "machine_learning.overfitting"),
    ("machine_learning.supervised_learning", "machine_learning.image_classification"),
    ("machine_learning.features_labels", "machine_learning.data_bias"),
    ("machine_learning.supervised_learning", "machine_learning.neural_network_basics"),
    ("generative_ai.prompt_basics", "generative_ai.hallucination"),
    ("generative_ai.hallucination", "generative_ai.responsible_use"),
    ("generative_ai.responsible_use", "generative_ai.copyright_originality"),
    ("data_literacy.privacy_basics", "generative_ai.responsible_use"),
    ("sorting.bubble_sort", "sorting.selection_sort"),
    ("searching.linear_search", "searching.binary_search"),
    ("ai_overview.what_is_ai", "machine_learning.features_labels"),
    ("ai_overview.what_is_ai", "generative_ai.llm_basics"),
    ("generative_ai.llm_basics", "generative_ai.prompt_basics"),
    ("machine_learning.image_classification", "computer_vision.object_detection"),
    ("nlp.text_tokenize", "nlp.sentiment"),
    ("ethics_safety.ai_ethics_intro", "ethics_safety.fairness"),
    ("digital_citizenship.media_literacy", "digital_citizenship.fake_news"),
    ("programming.scratch_basics", "programming.python_intro"),
    ("computing.algorithm_basics", "algorithms.algo_in_life"),
]

RELATED = [
    ("machine_learning.image_classification", "machine_learning.classification_regression"),
    ("machine_learning.data_bias", "generative_ai.responsible_use"),
    ("data_literacy.what_is_data", "data_literacy.privacy_basics"),
    ("generative_ai.hallucination", "ethics_safety.misinformation"),
    ("computer_vision.face_recognition", "ethics_safety.surveillance"),
]


def main() -> None:
    categories: list[dict] = []
    points: list[dict] = []
    edges: list[dict] = []

    for suffix, title, stage, diff in CATEGORIES:
        cat_code = f"category.{suffix}"
        categories.append(
            {
                "code": cat_code,
                "title": title,
                "stage": stage,
                "difficulty": diff,
                "kind": "CATEGORY",
            }
        )
        for slug, ptitle, pstage, pdiff in TOPICS[suffix]:
            code = LEGACY.get((suffix, slug), f"{suffix}.{slug}")
            points.append(
                {
                    "code": code,
                    "title": ptitle,
                    "stage": pstage,
                    "difficulty": pdiff,
                    "kind": "TOPIC",
                    "categoryCode": cat_code,
                    "categoryTitle": title,
                }
            )
            edges.append({"from": cat_code, "to": code, "relation": "HAS_CHILD"})

    for a, b in PREREQS:
        edges.append({"from": a, "to": b, "relation": "PREREQUISITE_OF"})
    for a, b in RELATED:
        edges.append({"from": a, "to": b, "relation": "RELATED_TO"})

    catalog = {
        "version": 3,
        "categories": categories,
        "points": points,
        "edges": edges,
    }

    # scripts/ -> k12-agent-runtime -> ai-services -> repo root
    repo_root = Path(__file__).resolve().parents[3]
    learning_root = repo_root / "backend" / "k12-learning-service"
    # 权威源：Learning 服务 classpath（进程只读这份）
    out = learning_root / "src/main/resources/knowledge/ai_literacy_catalog.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    # 运维镜像（非运行时）：仓库根 sql/neo4j/
    sql_copy = repo_root / "sql" / "neo4j" / "ai_literacy_catalog.json"
    sql_copy.parent.mkdir(parents=True, exist_ok=True)
    sql_copy.write_text(out.read_text(encoding="utf-8"), encoding="utf-8")

    print(f"categories={len(categories)} points={len(points)} edges={len(edges)}")
    print(f"total_nodes={len(categories) + len(points)}")
    print(f"wrote SSOT {out}")
    print(f"wrote mirror {sql_copy}")
    print("NOTE: 生成器若仍输出英文 stage，请勿覆盖已手工维护的中文 stages；优先改权威 JSON。")


if __name__ == "__main__":
    main()
